// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    BasicBtn: typeof import('./src/components/Buttons/BasicBtn.vue')['default']
    BasicComponents: typeof import('./src/components/Form/BasicComponents.vue')['default']
    BasicContent: typeof import('./src/components/Content/BasicContent.vue')['default']
    BasicForm: typeof import('./src/components/Form/BasicForm.vue')['default']
    BasicModal: typeof import('./src/components/Modal/BasicModal.vue')['default']
    BasicPagination: typeof import('./src/components/Pagination/BasicPagination.vue')['default']
    BasicSearch: typeof import('./src/components/Search/BasicSearch.vue')['default']
    BasicTable: typeof import('./src/components/Table/BasicTable.vue')['default']
    Copy: typeof import('./src/components/Copy/index.vue')['default']
    CopyBtn: typeof import('./src/components/Buttons/CopyBtn.vue')['default']
    DeleteBtn: typeof import('./src/components/Buttons/DeleteBtn.vue')['default']
    Echarts: typeof import('./src/components/Echarts/index.vue')['default']
    Fullscreen: typeof import('./src/components/Fullscreen/index.vue')['default']
    GlobalSearch: typeof import('./src/components/GlobalSearch/index.vue')['default']
    Icon: typeof import('./src/components/Icon/index.vue')['default']
    Line: typeof import('./src/components/Echarts/Line.vue')['default']
    Pie: typeof import('./src/components/Echarts/Pie.vue')['default']
    SearchFooter: typeof import('./src/components/GlobalSearch/components/SearchFooter.vue')['default']
    SearchModal: typeof import('./src/components/GlobalSearch/components/SearchModal.vue')['default']
    SearchResult: typeof import('./src/components/GlobalSearch/components/SearchResult.vue')['default']
    UpdateBtn: typeof import('./src/components/Buttons/UpdateBtn.vue')['default']
    UpdatePassword: typeof import('./src/components/UpdatePassword/index.vue')['default']
  }
}

export { }
