// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    AMenuItem: typeof import('ant-design-vue/es')['MenuItem']
    ASubMenu: typeof import('ant-design-vue/es')['SubMenu']
    BasicComponents: typeof import('./src/components/Basics/BasicComponents.vue')['default']
    'BasicComponents copy': typeof import('./src/components/Basics/BasicComponents copy.vue')['default']
    BasicContent: typeof import('./src/components/Basics/BasicContent.vue')['default']
    BasicForm: typeof import('./src/components/Basics/BasicForm.vue')['default']
    BasicModal: typeof import('./src/components/Basics/BasicModal.vue')['default']
    BasicPagination: typeof import('./src/components/Basics/BasicPagination.vue')['default']
    BasicTable: typeof import('./src/components/Basics/BasicTable.vue')['default']
    DeleteBtn: typeof import('./src/components/Buttons/DeleteBtn.vue')['default']
    Fullscreen: typeof import('./src/components/Fullscreen/index.vue')['default']
    GlobalSearch: typeof import('./src/components/GlobalSearch/index.vue')['default']
    Search: typeof import('./src/components/Search/index.vue')['default']
    SearchFooter: typeof import('./src/components/GlobalSearch/components/SearchFooter.vue')['default']
    SearchInput: typeof import('./src/components/GlobalSearch/components/SearchInput.vue')['default']
    SearchModal: typeof import('./src/components/GlobalSearch/components/SearchModal.vue')['default']
    SearchResult: typeof import('./src/components/GlobalSearch/components/SearchResult.vue')['default']
    SearhModel: typeof import('./src/components/GlobalSearch/components/SearhModel.vue')['default']
    UpdateBtn: typeof import('./src/components/Buttons/UpdateBtn.vue')['default']
    UpdatePassword: typeof import('./src/components/UpdatePassword/index.vue')['default']
    'UpdatePassword copy': typeof import('./src/components/UpdatePassword copy.vue')['default']
  }
}

export { }
